# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sciafeed/designer/download_hiscentral_window.ui.xml'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(480, 640)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(288, 600, 178, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.download_hiscentral_close = QtGui.QPushButton(self.layoutWidget)
        self.download_hiscentral_close.setEnabled(True)
        self.download_hiscentral_close.setCheckable(True)
        self.download_hiscentral_close.setChecked(False)
        self.download_hiscentral_close.setAutoExclusive(False)
        self.download_hiscentral_close.setAutoDefault(False)
        self.download_hiscentral_close.setFlat(False)
        self.download_hiscentral_close.setObjectName(_fromUtf8("download_hiscentral_close"))
        self.horizontalLayout_4.addWidget(self.download_hiscentral_close)
        self.download_hiscentral_run = QtGui.QPushButton(self.layoutWidget)
        self.download_hiscentral_run.setCheckable(True)
        self.download_hiscentral_run.setObjectName(_fromUtf8("download_hiscentral_run"))
        self.horizontalLayout_4.addWidget(self.download_hiscentral_run)
        self.layoutWidget_2 = QtGui.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(28, 420, 431, 171))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.textEdit_2 = QtGui.QTextEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.verticalLayout_3.addWidget(self.textEdit_2)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(28, 80, 381, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.layoutWidget_3 = QtGui.QWidget(Form)
        self.layoutWidget_3.setGeometry(QtCore.QRect(28, 130, 159, 29))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox = QtGui.QComboBox(self.layoutWidget_3)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox)
        self.layoutWidget_4 = QtGui.QWidget(Form)
        self.layoutWidget_4.setGeometry(QtCore.QRect(29, 310, 421, 29))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.destination_folder_edit = QtGui.QLineEdit(self.layoutWidget_4)
        self.destination_folder_edit.setObjectName(_fromUtf8("destination_folder_edit"))
        self.horizontalLayout_2.addWidget(self.destination_folder_edit)
        self.select_folder_button = QtGui.QPushButton(self.layoutWidget_4)
        self.select_folder_button.setObjectName(_fromUtf8("select_folder_button"))
        self.horizontalLayout_2.addWidget(self.select_folder_button)
        self.layoutWidget_5 = QtGui.QWidget(Form)
        self.layoutWidget_5.setGeometry(QtCore.QRect(248, 130, 206, 161))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.textEdit = QtGui.QTextEdit(self.layoutWidget_5)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_2.addWidget(self.textEdit)
        self.title_frame = QtGui.QFrame(Form)
        self.title_frame.setGeometry(QtCore.QRect(28, 20, 431, 51))
        self.title_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.title_frame.setObjectName(_fromUtf8("title_frame"))
        self.Title = QtGui.QLabel(self.title_frame)
        self.Title.setGeometry(QtCore.QRect(20, 10, 251, 41))
        self.Title.setObjectName(_fromUtf8("Title"))
        self.layoutWidget_6 = QtGui.QWidget(Form)
        self.layoutWidget_6.setGeometry(QtCore.QRect(28, 180, 181, 101))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget_6)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.listWidget = QtGui.QListWidget(self.layoutWidget_6)
        self.listWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listWidget.setModelColumn(0)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout.addWidget(self.listWidget)
        self.layoutWidget_7 = QtGui.QWidget(Form)
        self.layoutWidget_7.setGeometry(QtCore.QRect(30, 360, 421, 35))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.download_hiscentral_close.setText(_translate("Form", "Chiudi", None))
        self.download_hiscentral_run.setText(_translate("Form", "Avvia", None))
        self.label_7.setText(_translate("Form", "Output processamento", None))
        self.textEdit_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.label_6.setText(_translate("Form", "Scaricamento di dati attraverso il servizio HISCENTRAL", None))
        self.label_2.setText(_translate("Form", "Regione", None))
        self.comboBox.setItemText(0, _translate("Form", "Lazio", None))
        self.comboBox.setItemText(1, _translate("Form", "Calabria", None))
        self.comboBox.setItemText(2, _translate("Form", "Piemonte", None))
        self.label_4.setText(_translate("Form", "Destinazione", None))
        self.select_folder_button.setText(_translate("Form", "Cerca...", None))
        self.label_3.setText(_translate("Form", "lista stazioni (1 per riga)", None))
        self.Title.setText(_translate("Form", "<html><head/><body><p><span style=\" font-family:\'Sans Serif\'; font-size:16pt;\">Download HISCENTRAL</span></p></body></html>", None))
        self.label.setText(_translate("Form", "Variabile", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "Precipitazione", None))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "Temperatura massima", None))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "Temperatura minima", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("Form", "File di report", None))

