# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download_hiscentral_window.ui.xml'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_download_hiscentral_form(object):
    def setupUi(self, download_hiscentral_form):
        download_hiscentral_form.setObjectName(_fromUtf8("download_hiscentral_form"))
        download_hiscentral_form.resize(490, 640)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(download_hiscentral_form.sizePolicy().hasHeightForWidth())
        download_hiscentral_form.setSizePolicy(sizePolicy)
        download_hiscentral_form.setMinimumSize(QtCore.QSize(490, 640))
        download_hiscentral_form.setMaximumSize(QtCore.QSize(490, 640))
        self.layoutWidget = QtGui.QWidget(download_hiscentral_form)
        self.layoutWidget.setGeometry(QtCore.QRect(288, 600, 178, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.script_close = QtGui.QPushButton(self.layoutWidget)
        self.script_close.setEnabled(True)
        self.script_close.setCheckable(True)
        self.script_close.setChecked(False)
        self.script_close.setAutoExclusive(False)
        self.script_close.setAutoDefault(False)
        self.script_close.setFlat(False)
        self.script_close.setObjectName(_fromUtf8("script_close"))
        self.horizontalLayout_4.addWidget(self.script_close)
        self.script_run = QtGui.QPushButton(self.layoutWidget)
        self.script_run.setCheckable(True)
        self.script_run.setObjectName(_fromUtf8("script_run"))
        self.horizontalLayout_4.addWidget(self.script_run)
        self.layoutWidget_2 = QtGui.QWidget(download_hiscentral_form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(28, 420, 431, 171))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.output_console = QtGui.QTextEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(False)
        font.setWeight(50)
        self.output_console.setFont(font)
        self.output_console.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.output_console.setReadOnly(True)
        self.output_console.setObjectName(_fromUtf8("output_console"))
        self.verticalLayout_3.addWidget(self.output_console)
        self.download_hiscentral_description = QtGui.QLabel(download_hiscentral_form)
        self.download_hiscentral_description.setGeometry(QtCore.QRect(28, 80, 381, 17))
        self.download_hiscentral_description.setObjectName(_fromUtf8("download_hiscentral_description"))
        self.layoutWidget_4 = QtGui.QWidget(download_hiscentral_form)
        self.layoutWidget_4.setGeometry(QtCore.QRect(29, 310, 421, 29))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.input_destination = QtGui.QLineEdit(self.layoutWidget_4)
        self.input_destination.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.input_destination.setReadOnly(False)
        self.input_destination.setObjectName(_fromUtf8("input_destination"))
        self.horizontalLayout_2.addWidget(self.input_destination)
        self.select_destination_button = QtGui.QPushButton(self.layoutWidget_4)
        self.select_destination_button.setObjectName(_fromUtf8("select_destination_button"))
        self.horizontalLayout_2.addWidget(self.select_destination_button)
        self.layoutWidget_5 = QtGui.QWidget(download_hiscentral_form)
        self.layoutWidget_5.setGeometry(QtCore.QRect(248, 120, 206, 171))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.input_locations = QtGui.QTextEdit(self.layoutWidget_5)
        self.input_locations.setObjectName(_fromUtf8("input_locations"))
        self.verticalLayout_2.addWidget(self.input_locations)
        self.title_frame = QtGui.QFrame(download_hiscentral_form)
        self.title_frame.setGeometry(QtCore.QRect(28, 20, 431, 51))
        self.title_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.title_frame.setObjectName(_fromUtf8("title_frame"))
        self.Title = QtGui.QLabel(self.title_frame)
        self.Title.setGeometry(QtCore.QRect(20, 10, 251, 41))
        self.Title.setObjectName(_fromUtf8("Title"))
        self.layoutWidget_6 = QtGui.QWidget(download_hiscentral_form)
        self.layoutWidget_6.setGeometry(QtCore.QRect(28, 180, 201, 101))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget_6)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.input_variables = QtGui.QListWidget(self.layoutWidget_6)
        self.input_variables.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.input_variables.setModelColumn(0)
        self.input_variables.setObjectName(_fromUtf8("input_variables"))
        item = QtGui.QListWidgetItem()
        self.input_variables.addItem(item)
        item = QtGui.QListWidgetItem()
        self.input_variables.addItem(item)
        item = QtGui.QListWidgetItem()
        self.input_variables.addItem(item)
        self.verticalLayout.addWidget(self.input_variables)
        self.layoutWidget_7 = QtGui.QWidget(download_hiscentral_form)
        self.layoutWidget_7.setGeometry(QtCore.QRect(30, 360, 421, 35))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.input_report = QtGui.QLineEdit(self.layoutWidget_7)
        self.input_report.setObjectName(_fromUtf8("input_report"))
        self.horizontalLayout_3.addWidget(self.input_report)
        self.select_report_button = QtGui.QPushButton(self.layoutWidget_7)
        self.select_report_button.setObjectName(_fromUtf8("select_report_button"))
        self.horizontalLayout_3.addWidget(self.select_report_button)
        self.layoutWidget1 = QtGui.QWidget(download_hiscentral_form)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 120, 201, 52))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.input_region = QtGui.QComboBox(self.layoutWidget1)
        self.input_region.setObjectName(_fromUtf8("input_region"))
        self.verticalLayout_4.addWidget(self.input_region)

        self.retranslateUi(download_hiscentral_form)
        QtCore.QMetaObject.connectSlotsByName(download_hiscentral_form)
        download_hiscentral_form.setTabOrder(self.input_region, self.input_variables)
        download_hiscentral_form.setTabOrder(self.input_variables, self.input_locations)
        download_hiscentral_form.setTabOrder(self.input_locations, self.input_destination)
        download_hiscentral_form.setTabOrder(self.input_destination, self.select_destination_button)
        download_hiscentral_form.setTabOrder(self.select_destination_button, self.input_report)
        download_hiscentral_form.setTabOrder(self.input_report, self.select_report_button)
        download_hiscentral_form.setTabOrder(self.select_report_button, self.output_console)
        download_hiscentral_form.setTabOrder(self.output_console, self.script_close)
        download_hiscentral_form.setTabOrder(self.script_close, self.script_run)

    def retranslateUi(self, download_hiscentral_form):
        download_hiscentral_form.setWindowTitle(_translate("download_hiscentral_form", "Download HISCENTRAL", None))
        self.script_close.setText(_translate("download_hiscentral_form", "Chiudi", None))
        self.script_run.setText(_translate("download_hiscentral_form", "Avvia", None))
        self.label_7.setText(_translate("download_hiscentral_form", "Output processamento", None))
        self.output_console.setHtml(_translate("download_hiscentral_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#ffffff;\">READY</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; color:#ffffff;\"><br /></p></body></html>", None))
        self.download_hiscentral_description.setText(_translate("download_hiscentral_form", "Scaricamento di dati attraverso il servizio HISCENTRAL", None))
        self.label_4.setText(_translate("download_hiscentral_form", "Destinazione", None))
        self.select_destination_button.setText(_translate("download_hiscentral_form", "Cerca...", None))
        self.label_3.setText(_translate("download_hiscentral_form", "lista stazioni (1 per riga)", None))
        self.Title.setText(_translate("download_hiscentral_form", "<html><head/><body><p><span style=\" font-family:\'Sans Serif\'; font-size:16pt;\">Download HISCENTRAL</span></p></body></html>", None))
        self.label.setText(_translate("download_hiscentral_form", "Variabile", None))
        __sortingEnabled = self.input_variables.isSortingEnabled()
        self.input_variables.setSortingEnabled(False)
        item = self.input_variables.item(0)
        item.setText(_translate("download_hiscentral_form", "Precipitazione", None))
        item = self.input_variables.item(1)
        item.setText(_translate("download_hiscentral_form", "Temperatura massima", None))
        item = self.input_variables.item(2)
        item.setText(_translate("download_hiscentral_form", "Temperatura minima", None))
        self.input_variables.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("download_hiscentral_form", "File di report", None))
        self.select_report_button.setText(_translate("download_hiscentral_form", "Cerca...", None))
        self.label_2.setText(_translate("download_hiscentral_form", "Regione", None))

