# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'make_reports.ui.xml'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_make_reports_form(object):
    def setupUi(self, make_reports_form):
        make_reports_form.setObjectName(_fromUtf8("make_reports_form"))
        make_reports_form.resize(490, 640)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(make_reports_form.sizePolicy().hasHeightForWidth())
        make_reports_form.setSizePolicy(sizePolicy)
        make_reports_form.setMinimumSize(QtCore.QSize(490, 640))
        make_reports_form.setMaximumSize(QtCore.QSize(490, 640))
        self.layoutWidget = QtGui.QWidget(make_reports_form)
        self.layoutWidget.setGeometry(QtCore.QRect(288, 600, 178, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.script_close = QtGui.QPushButton(self.layoutWidget)
        self.script_close.setEnabled(True)
        self.script_close.setCheckable(True)
        self.script_close.setChecked(False)
        self.script_close.setAutoExclusive(False)
        self.script_close.setAutoDefault(False)
        self.script_close.setFlat(False)
        self.script_close.setObjectName(_fromUtf8("script_close"))
        self.horizontalLayout_4.addWidget(self.script_close)
        self.script_run = QtGui.QPushButton(self.layoutWidget)
        self.script_run.setCheckable(True)
        self.script_run.setObjectName(_fromUtf8("script_run"))
        self.horizontalLayout_4.addWidget(self.script_run)
        self.layoutWidget_2 = QtGui.QWidget(make_reports_form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(28, 370, 431, 221))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.output_console = QtGui.QTextEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(False)
        font.setWeight(50)
        self.output_console.setFont(font)
        self.output_console.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.output_console.setReadOnly(True)
        self.output_console.setObjectName(_fromUtf8("output_console"))
        self.verticalLayout_3.addWidget(self.output_console)
        self.download_er_description = QtGui.QLabel(make_reports_form)
        self.download_er_description.setGeometry(QtCore.QRect(30, 80, 441, 17))
        self.download_er_description.setObjectName(_fromUtf8("download_er_description"))
        self.title_frame = QtGui.QFrame(make_reports_form)
        self.title_frame.setGeometry(QtCore.QRect(28, 20, 431, 51))
        self.title_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.title_frame.setObjectName(_fromUtf8("title_frame"))
        self.Title = QtGui.QLabel(self.title_frame)
        self.Title.setGeometry(QtCore.QRect(20, 10, 341, 41))
        self.Title.setObjectName(_fromUtf8("Title"))
        self.widget = QtGui.QWidget(make_reports_form)
        self.widget.setGeometry(QtCore.QRect(30, 110, 431, 241))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.select_file = QtGui.QRadioButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_file.sizePolicy().hasHeightForWidth())
        self.select_file.setSizePolicy(sizePolicy)
        self.select_file.setChecked(True)
        self.select_file.setObjectName(_fromUtf8("select_file"))
        self.horizontalLayout_2.addWidget(self.select_file)
        spacerItem = QtGui.QSpacerItem(318, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_input_file = QtGui.QLabel(self.widget)
        self.label_input_file.setObjectName(_fromUtf8("label_input_file"))
        self.gridLayout.addWidget(self.label_input_file, 0, 0, 1, 1)
        self.input_file = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_file.sizePolicy().hasHeightForWidth())
        self.input_file.setSizePolicy(sizePolicy)
        self.input_file.setMinimumSize(QtCore.QSize(240, 0))
        self.input_file.setObjectName(_fromUtf8("input_file"))
        self.gridLayout.addWidget(self.input_file, 0, 1, 1, 1)
        self.select_input_file_button = QtGui.QPushButton(self.widget)
        self.select_input_file_button.setObjectName(_fromUtf8("select_input_file_button"))
        self.gridLayout.addWidget(self.select_input_file_button, 0, 2, 1, 1)
        self.label_output_file = QtGui.QLabel(self.widget)
        self.label_output_file.setObjectName(_fromUtf8("label_output_file"))
        self.gridLayout.addWidget(self.label_output_file, 1, 0, 1, 1)
        self.output_file = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_file.sizePolicy().hasHeightForWidth())
        self.output_file.setSizePolicy(sizePolicy)
        self.output_file.setMinimumSize(QtCore.QSize(240, 0))
        self.output_file.setObjectName(_fromUtf8("output_file"))
        self.gridLayout.addWidget(self.output_file, 1, 1, 1, 1)
        self.select_output_file_button = QtGui.QPushButton(self.widget)
        self.select_output_file_button.setObjectName(_fromUtf8("select_output_file_button"))
        self.gridLayout.addWidget(self.select_output_file_button, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.select_folder = QtGui.QRadioButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_folder.sizePolicy().hasHeightForWidth())
        self.select_folder.setSizePolicy(sizePolicy)
        self.select_folder.setObjectName(_fromUtf8("select_folder"))
        self.horizontalLayout.addWidget(self.select_folder)
        spacerItem1 = QtGui.QSpacerItem(318, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_input_folder = QtGui.QLabel(self.widget)
        self.label_input_folder.setObjectName(_fromUtf8("label_input_folder"))
        self.gridLayout_2.addWidget(self.label_input_folder, 0, 0, 1, 1)
        self.input_folder = QtGui.QLineEdit(self.widget)
        self.input_folder.setObjectName(_fromUtf8("input_folder"))
        self.gridLayout_2.addWidget(self.input_folder, 0, 1, 1, 1)
        self.select_input_folder_button = QtGui.QPushButton(self.widget)
        self.select_input_folder_button.setObjectName(_fromUtf8("select_input_folder_button"))
        self.gridLayout_2.addWidget(self.select_input_folder_button, 0, 2, 1, 1)
        self.label_output_folder = QtGui.QLabel(self.widget)
        self.label_output_folder.setObjectName(_fromUtf8("label_output_folder"))
        self.gridLayout_2.addWidget(self.label_output_folder, 1, 0, 1, 1)
        self.output_folder = QtGui.QLineEdit(self.widget)
        self.output_folder.setObjectName(_fromUtf8("output_folder"))
        self.gridLayout_2.addWidget(self.output_folder, 1, 1, 1, 1)
        self.select_output_folder_button = QtGui.QPushButton(self.widget)
        self.select_output_folder_button.setObjectName(_fromUtf8("select_output_folder_button"))
        self.gridLayout_2.addWidget(self.select_output_folder_button, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_report = QtGui.QLabel(self.widget)
        self.label_report.setObjectName(_fromUtf8("label_report"))
        self.horizontalLayout_3.addWidget(self.label_report)
        self.input_report = QtGui.QLineEdit(self.widget)
        self.input_report.setObjectName(_fromUtf8("input_report"))
        self.horizontalLayout_3.addWidget(self.input_report)
        self.select_report_button = QtGui.QPushButton(self.widget)
        self.select_report_button.setObjectName(_fromUtf8("select_report_button"))
        self.horizontalLayout_3.addWidget(self.select_report_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(make_reports_form)
        QtCore.QMetaObject.connectSlotsByName(make_reports_form)
        make_reports_form.setTabOrder(self.input_report, self.select_report_button)
        make_reports_form.setTabOrder(self.select_report_button, self.output_console)
        make_reports_form.setTabOrder(self.output_console, self.script_close)
        make_reports_form.setTabOrder(self.script_close, self.script_run)

    def retranslateUi(self, make_reports_form):
        make_reports_form.setWindowTitle(_translate("make_reports_form", "Generazione File normalizzati", None))
        self.script_close.setText(_translate("make_reports_form", "Chiudi", None))
        self.script_run.setText(_translate("make_reports_form", "Avvia", None))
        self.label_7.setText(_translate("make_reports_form", "Output processamento", None))
        self.output_console.setHtml(_translate("make_reports_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#ffffff;\">READY</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; color:#ffffff;\"><br /></p></body></html>", None))
        self.download_er_description.setText(_translate("make_reports_form", "Generazione di file normalizzati CSV contenenti dati climatici", None))
        self.Title.setText(_translate("make_reports_form", "<html><head/><body><p><span style=\" font-family:\'Sans Serif\'; font-size:16pt;\">Generazione File normalizzati</span></p></body></html>", None))
        self.select_file.setText(_translate("make_reports_form", "File", None))
        self.label_input_file.setText(_translate("make_reports_form", "Input", None))
        self.select_input_file_button.setText(_translate("make_reports_form", "Cerca...", None))
        self.label_output_file.setText(_translate("make_reports_form", "Destinazione", None))
        self.select_output_file_button.setText(_translate("make_reports_form", "Cerca...", None))
        self.select_folder.setText(_translate("make_reports_form", "Cartella", None))
        self.label_input_folder.setText(_translate("make_reports_form", "Input", None))
        self.select_input_folder_button.setText(_translate("make_reports_form", "Cerca...", None))
        self.label_output_folder.setText(_translate("make_reports_form", "Destinazione", None))
        self.select_output_folder_button.setText(_translate("make_reports_form", "Cerca...", None))
        self.label_report.setText(_translate("make_reports_form", "File di report", None))
        self.select_report_button.setText(_translate("make_reports_form", "Cerca...", None))

