# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'make_report.ui.xml'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_make_report_form(object):
    def setupUi(self, make_report_form):
        make_report_form.setObjectName(_fromUtf8("make_report_form"))
        make_report_form.resize(490, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(make_report_form.sizePolicy().hasHeightForWidth())
        make_report_form.setSizePolicy(sizePolicy)
        make_report_form.setMinimumSize(QtCore.QSize(490, 640))
        make_report_form.setMaximumSize(QtCore.QSize(490, 640))
        self.layoutWidget = QtWidgets.QWidget(make_report_form)
        self.layoutWidget.setGeometry(QtCore.QRect(288, 600, 178, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        #self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.script_close = QtWidgets.QPushButton(self.layoutWidget)
        self.script_close.setEnabled(True)
        self.script_close.setCheckable(True)
        self.script_close.setChecked(False)
        self.script_close.setAutoExclusive(False)
        self.script_close.setAutoDefault(False)
        self.script_close.setFlat(False)
        self.script_close.setObjectName(_fromUtf8("script_close"))
        self.horizontalLayout_4.addWidget(self.script_close)
        self.script_run = QtWidgets.QPushButton(self.layoutWidget)
        self.script_run.setCheckable(True)
        self.script_run.setObjectName(_fromUtf8("script_run"))
        self.horizontalLayout_4.addWidget(self.script_run)
        self.layoutWidget_2 = QtWidgets.QWidget(make_report_form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(28, 270, 431, 321))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        #self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.output_console = QtWidgets.QTextEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(False)
        font.setWeight(50)
        self.output_console.setFont(font)
        self.output_console.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.output_console.setReadOnly(True)
        self.output_console.setObjectName(_fromUtf8("output_console"))
        self.verticalLayout_3.addWidget(self.output_console)
        self.download_er_description = QtWidgets.QLabel(make_report_form)
        self.download_er_description.setGeometry(QtCore.QRect(28, 80, 441, 17))
        self.download_er_description.setObjectName(_fromUtf8("download_er_description"))
        self.title_frame = QtWidgets.QFrame(make_report_form)
        self.title_frame.setGeometry(QtCore.QRect(28, 20, 431, 51))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName(_fromUtf8("title_frame"))
        self.Title = QtWidgets.QLabel(self.title_frame)
        self.Title.setGeometry(QtCore.QRect(20, 10, 341, 41))
        self.Title.setObjectName(_fromUtf8("Title"))
        self.layoutWidget_7 = QtWidgets.QWidget(make_report_form)
        self.layoutWidget_7.setGeometry(QtCore.QRect(30, 210, 421, 35))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        #self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.input_report = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.input_report.setObjectName(_fromUtf8("input_report"))
        self.horizontalLayout_3.addWidget(self.input_report)
        self.select_report_button = QtWidgets.QPushButton(self.layoutWidget_7)
        self.select_report_button.setObjectName(_fromUtf8("select_report_button"))
        self.horizontalLayout_3.addWidget(self.select_report_button)
        self.widget = QtWidgets.QWidget(make_report_form)
        self.widget.setGeometry(QtCore.QRect(30, 120, 422, 29))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        #self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.select_file = QtWidgets.QRadioButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_file.sizePolicy().hasHeightForWidth())
        self.select_file.setSizePolicy(sizePolicy)
        self.select_file.setChecked(True)
        self.select_file.setObjectName(_fromUtf8("select_file"))
        self.horizontalLayout.addWidget(self.select_file)
        self.input_file = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_file.sizePolicy().hasHeightForWidth())
        self.input_file.setSizePolicy(sizePolicy)
        self.input_file.setMinimumSize(QtCore.QSize(240, 0))
        self.input_file.setObjectName(_fromUtf8("input_file"))
        self.horizontalLayout.addWidget(self.input_file)
        self.select_input_file_button = QtWidgets.QPushButton(self.widget)
        self.select_input_file_button.setObjectName(_fromUtf8("select_input_file_button"))
        self.horizontalLayout.addWidget(self.select_input_file_button)
        self.widget1 = QtWidgets.QWidget(make_report_form)
        self.widget1.setGeometry(QtCore.QRect(30, 160, 421, 29))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        #self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.select_folder = QtWidgets.QRadioButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_folder.sizePolicy().hasHeightForWidth())
        self.select_folder.setSizePolicy(sizePolicy)
        self.select_folder.setObjectName(_fromUtf8("select_folder"))
        self.horizontalLayout_2.addWidget(self.select_folder)
        self.input_folder = QtWidgets.QLineEdit(self.widget1)
        self.input_folder.setObjectName(_fromUtf8("input_folder"))
        self.horizontalLayout_2.addWidget(self.input_folder)
        self.select_input_folder_button = QtWidgets.QPushButton(self.widget1)
        self.select_input_folder_button.setObjectName(_fromUtf8("select_input_folder_button"))
        self.horizontalLayout_2.addWidget(self.select_input_folder_button)

        self.retranslateUi(make_report_form)
        QtCore.QMetaObject.connectSlotsByName(make_report_form)
        make_report_form.setTabOrder(self.input_report, self.select_report_button)
        make_report_form.setTabOrder(self.select_report_button, self.output_console)
        make_report_form.setTabOrder(self.output_console, self.script_close)
        make_report_form.setTabOrder(self.script_close, self.script_run)

    def retranslateUi(self, make_report_form):
        make_report_form.setWindowTitle(_translate("make_report_form", "Analisi file sorgenti", None))
        self.script_close.setText(_translate("make_report_form", "Chiudi", None))
        self.script_run.setText(_translate("make_report_form", "Avvia", None))
        self.label_7.setText(_translate("make_report_form", "Output processamento", None))
        self.output_console.setHtml(_translate("make_report_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#ffffff;\">READY</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; color:#ffffff;\"><br /></p></body></html>", None))
        self.download_er_description.setText(_translate("make_report_form", "Analisi dei file sorgenti contenenti dati climatici", None))
        self.Title.setText(_translate("make_report_form", "<html><head/><body><p><span style=\" font-family:\'Sans Serif\'; font-size:16pt;\">Analisi File sorgenti</span></p></body></html>", None))
        self.label_5.setText(_translate("make_report_form", "File di report", None))
        self.select_report_button.setText(_translate("make_report_form", "Cerca...", None))
        self.select_file.setText(_translate("make_report_form", "File", None))
        self.select_input_file_button.setText(_translate("make_report_form", "Cerca...", None))
        self.select_folder.setText(_translate("make_report_form", "Cartella", None))
        self.select_input_folder_button.setText(_translate("make_report_form", "Cerca...", None))

